### ISSUE TITLE
Transition publisher permissions from auth0 to roles

### ISSUE THREAD

**Issue by terryttsai** [Recidiviz/justice-counts#349] opened 2023-01-27 19:48 UTC
Show publisher permissions (like whether you're allowed to create a report or see all the agency settings) based on roles, not based on auth0 permissions.

**Comment by lilidworkin** [comment] 2023-01-29 21:22
@terryttsai I think this might be a duplicate of https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/justice-counts/344? If so feel free to pick one to close out!

**Closed** 2023-02-01 22:17 UTC
Labels: Team: Justice Counts
