### ISSUE TITLE
[Frontend] Explore alternatives to overflow containers/a way to better hide scrollbars

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#440] opened 2023-02-23 17:04 UTC

**Comment by lilidworkin** [comment] 2023-02-23 19:59
Closing as a duplicate of https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/gh/recidiviz/justice-counts/441

**Closed** 2023-02-28 15:14 UTC
Labels: Team: Justice Counts
